### ISSUE TITLE
Test Data throws error with latest udger-java version

### ISSUE THREAD

**Issue by baunz** [udger/test-data#3]
Hi,

when creating a parser from the test db with the latest udger-java `1.2.2`, the parsing gives the following error. 

````
Exception in thread "main" org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: udger_client_regex)
	at org.sqlite.core.DB.newSQLException(DB.java:909)
	at org.sqlite.core.DB.newSQLException(DB.java:921)
	at org.sqlite.core.DB.throwex(DB.java:886)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:127)
	at org.sqlite.core.DB.prepare(DB.java:227)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:81)
	at org.udger.parser.UdgerParser.prepareRegexpStruct(UdgerParser.java:433)
	at org.udger.parser.UdgerParser.access$000(UdgerParser.java:30)
	at org.udger.parser.UdgerParser$ParserDbData.prepare(UdgerParser.java:64)
	at org.udger.parser.UdgerParser.prepare(UdgerParser.java:566)
	at org.udger.parser.UdgerParser.parseUa(UdgerParser.java:199)
	at de.udger.TestUdger.main(TestUdger.java:16)
````
The test data is very useful in development or testing environments so it would be great it was still working there. Do you think this is possible?

Have a nice day,

Johannes

**Comment by mallat** [comment]
Can I know exactly what DB you used?

**Comment by baunz** [comment]
Sorry for the delay,

it was the file

https://github.com/udger/test-data/blob/master/data_v3/udgerdb_v3.dat

**Comment by mallat** [comment]
There is a "udger_client_regex" table in this database. There are all the necessary tables, but they are not filled with full/paid data. 
I think the mistake will be elsewhere.

**Comment by baunz** [comment]
Jaroslav, you are right, of course it was my mistake (the file was a zero byte file, something must have messed it up). Sorry for the mistake!
